### ISSUE TITLE
Missing outFile variable

### ISSUE THREAD

**Issue by MartinKjunior** [mhaft/DeepVess#1]
The script `prepareImage.m` never defines the variable `outFile` so `im = tifMotionRemoval(outFile);` doesn't run.

My input was:
```
prepareImage( ...
    1, ...
    0, ...
    1, ...
    1, ...
    'C:\Users\path\to\folder', ...
    '22_11_23_SR101_02.lif - Series008 - C=0.tif', ...
    [1 98], ...
    1)
```

**Comment by elinestas** [comment]
Have you found a solution to this?

**Comment by MartinKjunior** [comment]
> Have you found a solution to this?

No.
It shouldn't be too hard to write in a simple logic to substitute the missing outFile variable, which I assume is just a string with the folder path or file name that the output should be saved to, but I just used the Fiji (ImageJ) plugin to register a stack with SIFT since I was using Fiji to save my images as tif files instead of the microscope manufacturer's filetype. If you don't use the motion removal then the script runs just fine.

**Comment by mhaft** [comment]
Thank you, @elinestas and @MartinKjunior, for bringing this issue to my attention. This happened due to a change in the data flow design and a mismatch between the two designs. I just patched it and hope it works now.
